//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProvider.Amex {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MockData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MockData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataProvider.Amex.MockData", typeof(MockData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;validCards&quot;: &quot;yes&quot;,
        ///  &quot;invalidCards&quot;: [],
        ///  &quot;id&quot;: &quot;311913289&quot;,
        ///  &quot;info&quot;: &quot;ירוי        סינפיק&quot;,
        ///  &quot;Table1&quot;: [
        ///    {
        ///      &quot;cardNumber&quot;: &quot;6660&quot;,
        ///      &quot;cardName&quot;: &quot;אמק\&quot;ס BUSINESS זהב  &quot;,
        ///      &quot;paymentDate&quot;: &quot;02&quot;,
        ///      &quot;bankId&quot;: &quot;012&quot;,
        ///      &quot;bankBranchId&quot;: &quot;617&quot;,
        ///      &quot;bankAccountId&quot;: &quot;527482&quot;,
        ///      &quot;partnerName&quot;: &quot; &quot;,
        ///      &quot;connectionType&quot;: [],
        ///      &quot;userName&quot;: &quot;ירוי       סינפיק&quot;,
        ///      &quot;serviceType&quot;: &quot;191&quot;,
        ///      &quot;shiuch&quot;: &quot;04531&quot;,
        ///      &quot;stage&quot;: [],
        ///      &quot;returnCode&quot;: [],
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AmexCards {
            get {
                return ResourceManager.GetString("AmexCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Header&quot;:   {
        ///    &quot;Status&quot;: &quot;1&quot;,
        ///    &quot;Message&quot;: []
        ///  },
        ///  &quot;DealsListForDate_203Bean&quot;:   {
        ///    &quot;moed&quot;: &quot;022016&quot;,
        ///    &quot;payDay&quot;: &quot;02&quot;,
        ///    &quot;displayProperties&quot;:     [
        ///      &quot;קיפניס       יורי, חשבון 012-617-0527482, כרטיס 6660, ממועד 02/2016&quot;,
        ///      []
        ///    ],
        ///    &quot;isShowDealsInboundForCharge&quot;: &quot;yes&quot;,
        ///    &quot;isTooManyRecords&quot;: [],
        ///    &quot;isShowDealsInboundForInfo&quot;: &quot;NO&quot;,
        ///    &quot;selectedDateIndex&quot;: &quot;23&quot;,
        ///    &quot;startDate&quot;: [],
        ///    &quot;endDate&quot;: [],
        ///    &quot;dateList&quot;:     [
        ///      &quot;01/2018&quot;,
        ///      &quot;12/201 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CardTransactions1 {
            get {
                return ResourceManager.GetString("CardTransactions1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;Header&quot;:   {
        ///    &quot;Status&quot;: &quot;1&quot;,
        ///    &quot;Message&quot;: []
        ///  },
        ///  &quot;DealsListForDate_203Bean&quot;:   {
        ///    &quot;moed&quot;: &quot;022016&quot;,
        ///    &quot;payDay&quot;: &quot;02&quot;,
        ///    &quot;displayProperties&quot;:     [
        ///      &quot;קיפניס       אנסטסיה, חשבון 012-617-0527482, כרטיס 7840, ממועד 02/2016&quot;,
        ///      []
        ///    ],
        ///    &quot;isShowDealsInboundForCharge&quot;: &quot;yes&quot;,
        ///    &quot;isTooManyRecords&quot;: [],
        ///    &quot;isShowDealsInboundForInfo&quot;: &quot;NO&quot;,
        ///    &quot;selectedDateIndex&quot;: &quot;23&quot;,
        ///    &quot;startDate&quot;: [],
        ///    &quot;endDate&quot;: [],
        ///    &quot;dateList&quot;:     [
        ///      &quot;01/2018&quot;,
        ///      &quot;12/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CardTransactions2 {
            get {
                return ResourceManager.GetString("CardTransactions2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect vendor name - {0}.
        /// </summary>
        internal static string ProvidersFactory_GetVendorIdByName_Incorrect_vendor_name____0_ {
            get {
                return ResourceManager.GetString("ProvidersFactory_GetVendorIdByName_Incorrect_vendor_name____0_", resourceCulture);
            }
        }
    }
}
