//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProvider.Amex {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MockData {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MockData() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataProvider.Amex.MockData", typeof(MockData).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;validCards&quot;:&quot;yes&quot;,&quot;invalidCards&quot;:&quot;yes&quot;,&quot;id&quot;:&quot;311913289&quot;,&quot;info&quot;:&quot;קיפניס        יורי&quot;,&quot;Table1&quot;:[{&quot;cardNumber&quot;:&quot;2989&quot;,&quot;cardName&quot;:&quot;אמק\&quot;ס BUSINESS זהב  &quot;,&quot;paymentDate&quot;:&quot;02&quot;,&quot;bankId&quot;:&quot;012&quot;,&quot;bankBranchId&quot;:&quot;476&quot;,&quot;bankAccountId&quot;:&quot;129249&quot;,&quot;partnerName&quot;:&quot; &quot;,&quot;connectionType&quot;:null,&quot;userName&quot;:&quot;קיפניס       יורי&quot;,&quot;serviceType&quot;:&quot;191&quot;,&quot;kodShiuch&quot;:&quot;04531&quot;,&quot;kvutzatShiuch&quot;:&quot;169&quot;,&quot;holderId&quot;:&quot;311913289&quot;,&quot;expirationDate&quot;:&quot;30.09.2019&quot;,&quot;statusDate&quot;:&quot;01.01.0001&quot;,&quot;bankName&quot;:&quot;בנק הפועלים בעמ&quot;,&quot;club1&quot;:&quot;טכניון תארים גבוהים&quot;,&quot;logoSmal [rest of string was truncated]&quot;;.
        /// </summary>
        public static string AmexCards {
            get {
                return ResourceManager.GetString("AmexCards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///    &quot;Header&quot;: {
        ///        &quot;Status&quot;: &quot;1&quot;,
        ///        &quot;Message&quot;: null
        ///    },
        ///    &quot;CardsTransactionsListBean&quot;: {
        ///        &quot;month&quot;: &quot;10&quot;,
        ///        &quot;year&quot;: &quot;2016&quot;,
        ///        &quot;cardIdx&quot;: &quot;0&quot;,
        ///        &quot;moed&quot;: &quot;102016&quot;,
        ///        &quot;payDay&quot;: &quot;02&quot;,
        ///        &quot;selectedDateIndex&quot;: &quot;24&quot;,
        ///        &quot;dateList&quot;: [ &quot;09/2018&quot;, &quot;08/2018&quot;, &quot;07/2018&quot;, &quot;06/2018&quot;, &quot;05/2018&quot;, &quot;04/2018&quot;, &quot;03/2018&quot;, &quot;02/2018&quot;, &quot;01/2018&quot;, &quot;12/2017&quot;, &quot;11/2017&quot;, &quot;10/2017&quot;, &quot;09/2017&quot;, &quot;08/2017&quot;, &quot;07/2017&quot;, &quot;06/2017&quot;, &quot;05/2017&quot;, &quot;04/2017&quot;, &quot;03/2017&quot;, &quot;02/20 [rest of string was truncated]&quot;;.
        /// </summary>
        public static string CardTransactions1 {
            get {
                return ResourceManager.GetString("CardTransactions1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Header&quot;:{&quot;Status&quot;:&quot;1&quot;,&quot;Message&quot;:null},&quot;CardsTransactionsListBean&quot;:{&quot;month&quot;:&quot;10&quot;,&quot;year&quot;:&quot;2016&quot;,&quot;cardIdx&quot;:&quot;3&quot;,&quot;moed&quot;:&quot;102016&quot;,&quot;payDay&quot;:&quot;02&quot;,&quot;selectedDateIndex&quot;:&quot;24&quot;,&quot;dateList&quot;:[&quot;09/2018&quot;,&quot;08/2018&quot;,&quot;07/2018&quot;,&quot;06/2018&quot;,&quot;05/2018&quot;,&quot;04/2018&quot;,&quot;03/2018&quot;,&quot;02/2018&quot;,&quot;01/2018&quot;,&quot;12/2017&quot;,&quot;11/2017&quot;,&quot;10/2017&quot;,&quot;09/2017&quot;,&quot;08/2017&quot;,&quot;07/2017&quot;,&quot;06/2017&quot;,&quot;05/2017&quot;,&quot;04/2017&quot;,&quot;03/2017&quot;,&quot;02/2017&quot;,&quot;01/2017&quot;,&quot;12/2016&quot;,&quot;11/2016&quot;,&quot;10/2016&quot;,&quot;09/2016&quot;,&quot;08/2016&quot;,&quot;07/2016&quot;,&quot;06/2016&quot;,&quot;05/2016&quot;],&quot;totalChargeNis&quot;:&quot;2921.75&quot;,&quot;totalChargeDolla [rest of stri....
        /// </summary>
        public static string CardTransactions2 {
            get {
                return ResourceManager.GetString("CardTransactions2", resourceCulture);
            }
        }
    }
}
