//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataProvider.Hapoalim {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ServiceProviders {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ServiceProviders() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataProvider.Hapoalim.ServiceProviders", typeof(ServiceProviders).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4468617.
        /// </summary>
        public static string Amex {
            get {
                return ResourceManager.GetString("Amex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 812.
        /// </summary>
        public static string BankHapoalim {
            get {
                return ResourceManager.GetString("BankHapoalim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 18746.
        /// </summary>
        public static string Bezek {
            get {
                return ResourceManager.GetString("Bezek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 45642.
        /// </summary>
        public static string GaneiGalit {
            get {
                return ResourceManager.GetString("GaneiGalit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 25300.
        /// </summary>
        public static string Makabi {
            get {
                return ResourceManager.GetString("Makabi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 26000.
        /// </summary>
        public static string PoalimExpress {
            get {
                return ResourceManager.GetString("PoalimExpress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 8547.
        /// </summary>
        public static string Visa {
            get {
                return ResourceManager.GetString("Visa", resourceCulture);
            }
        }
    }
}
